---
abstract: 'An open source web-based network management tool.'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Netdisco
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Algorithm::Cron: 0.07
  AnyEvent: 7.05
  AnyEvent::DNS::EtcHosts: 0
  App::cpanminus: 1.6108
  App::local::lib::helper: 0.07
  Archive::Extract: 0
  DBD::Pg: 0
  DBD::SQLite: 1.37
  DBIx::Class: 0.0821
  DBIx::Class::Helpers: 2.018004
  Daemon::Control: 0.001
  Dancer: 1.3112
  Dancer::Plugin::Auth::Extensible: 0.3
  Dancer::Plugin::DBIC: 0.2001
  Dancer::Plugin::Passphrase: 2.0.1
  File::ShareDir: 1.03
  File::Slurp: 9999.19
  Guard: 1.022
  HTML::Parser: 3.7
  HTTP::Tiny: 0.029
  JSON: 0
  List::MoreUtils: 0.33
  MCE: 1.408
  MIME::Base64: 3.13
  Module::Load: 0.32
  Moo: 1.001
  Net::DNS: 0.72
  Net::Domain: 1.23
  Net::LDAP: 0
  Net::MAC: 2.103622
  Net::NBName: 0.26
  NetAddr::IP: 4.068
  Opcode: 1.07
  Path::Class: 0.32
  Plack: 1.0023
  Plack::Middleware::Expires: 0.03
  Role::Tiny: 1.002005
  SNMP::Info: 3.12
  SQL::Translator: 0.11016
  Socket6: 0.23
  Starman: 0.4008
  Template: 2.24
  Template::Plugin::CSV: 0.04
  Template::Plugin::Number::Format: 1.02
  Term::ReadLine: 0
  Term::UI: 0
  Try::Tiny: 0
  URI: 0
  URL::Encode: 0.01
  YAML: 0.84
  YAML::XS: 0.41
  namespace::clean: 0.24
  perl: 5.10.0
  version: 0.9902
resources:
  MailingList: https://lists.sourceforge.net/lists/listinfo/netdisco-users
  bugtracker: http://sourceforge.net/p/netdisco/bugs/
  homepage: http://netdisco.org/
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://git.code.sf.net/p/netdisco/netdisco-ng
version: 2.027005_001
