#
# NETDISCO 2 CONFIGURATION FILE
#
# Settings in this file override share/config.yml
# See App::Netdisco::Manual::Configuration for more info.

# ------------------
# ESSENTIAL SETTINGS
# ------------------

database:
  name: 'netdisco'
  user: 'changeme'
  pass: 'changeme'
  #host: 'localhost'

# --------------------
# RECOMMENDED SETTINGS
# --------------------

# set to "false" if you MUST maintain backwards compatibility
# with Netdisco 1.x web frontend.
# ```````````````````````````````````````````````````````````
safe_password_store: true

# will be stripped from fqdn when displayed in the web UI
# also, do not forget the leading dot.
# ```````````````````````````````````````````````````````
#domain_suffix: '.example.com'

# uncomment and set to true to globally disable authentication/loginr.
# create a user called "guest" if you want to assign port/admin rights.
# `````````````````````````````````````````````````````````````````````
#no_auth: false

# SNMP community string(s)
# ````````````````````````
#community: ['public']
#community_rw: ['private']

# daemon will keep netdisco up to date on this schedule
# `````````````````````````````````````````````````````
#housekeeping:
#  discoverall:
#    when: '5 7 * * *'
#  macwalk:
#    when:
#      min: 20
#  arpwalk:
#    when:
#      min: 50
#  nbtwalk:
#    when: '0 8,13,21 * * *'
#  expire:
#    when: '20 23 * * *'

# increase the performance of parallel DNS resolution for node
# names (the default is max_outstanding: 50)
# ````````````````````````````````````````````````````````````
#dns:
#  max_outstanding: 100
