# This is the main configuration file for Netdisco web and daemon apps
# all the settings in this file will be loaded at Dancer's startup.

# Web app env-related settings should go to environments/$env.yml

# application's name
appname: "Netdisco"

# The default web layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# web sessions stored on disk
session: "YAML"

# HTTP port to listen on
port: 5000

# logging format
logger_format: '[%P] %L @%D> %m'

# web output template settings
template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
    PRE_CHOMP: 1

# Netdisco stuff (can be overidden in the environment .yml)

web_plugins:
  - Inventory
  - Report::DuplexMismatch
  - AdminTask::PseudoDevice
  - AdminTask::Topology
  - AdminTask::JobQueue
  - Search::Device
  - Search::Node
  - Search::VLAN
  - Search::Port
  - Device::Details
  - Device::Ports
#  - Device::Modules
  - Device::Neighbors
  - Device::Addresses

discover_no: []
discover_only: []

snmpver: 2
snmpretries: 2
snmptimeout: 1000000

# If unset, Netdisco uses "NETDISCO_HOME/netdisco-mibs", assuming you're
# using the netdisco-deploy script to download MIBs there.  Otherwise, set
# this, for example:
#
# mibhome: /usr/share/netdisco/mibs

mibdirs:
  - cisco
  - rfc
  - net-snmp

community: ['public']
community_rw: ['private']

# rights control for Interactive jobs
vlanctl: 1
allow_uplinks: 0
portctl_nophones: 1
portctl_vlans: 1

# sleep time between polls of the database job queue
daemon_sleep_time: 5

# how many daemon processes for this node
daemon_interactives: 2
daemon_pollers: 2

# what housekeeping tasks should this node *schedule*
# (it only does them if daemon_pollers is non-zero)
#housekeeping:
#  discovernew:
#    device: '192.0.2.0'
#    when:
#      wday: 'wed'
#      hour: 14
#  backup:
#    when:
#      hour: 1
#  refresh:
#    when: '0 9 * * *'
#  arpwalk:
#    when:
#      min: 30
#  macwalk:
#    when:
#      hour: '*/2'
#  nbtwalk:
#    when:
#      hour: '8,13,21'
#  saveconfigs:
#    param: 61
#    when: '0 * * * *'
